
[build]
  publish = "out"
  command = "npm run examples"
  environment = { NODE_VERSION = "14.15.5" }
    
[[redirects]]
  from = "/examples/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=14400'''
